### ISSUE TITLE
Should we rename the repo to open-event-api-server ?

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-api#3931]
Since we have been making this into a pure API server, shouldn't the repository be renamed accordingly ? 

I suggest `open-event-api-server` or `open-event-api`. Both of these sound apt for the API Server. 

@fossasia/open-event-server-devs what do you think ?

**Comment by poush** [comment]
I think `open-event-api-server` looks good.

**Comment by aviaryan** [comment]
Agreed. `open-event-api` could also mean that this repo contains Open Event's API specifications. With `open-event-api-server`, there is no ambiguity.

**Comment by niranjan94** [comment]
@mariobehling could we rename this to `open-event-api-server` ? What do you think about it ?

**Comment by shubham-padia** [comment]
`open-event-api-server` looks good :+1:

**Comment by niranjan94** [comment]
@mariobehling could we rename this to `open-event-api-server` ? What do you think about it ?

**Comment by mariobehling** [comment]
@niranjan94 How about simply Open Event Server?

**Comment by SaptakS** [comment]
Closing this issue since the renaming and separating of new code and legacy code into different repo has been done.
