### ISSUE TITLE
Rename branches and clean up

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-api#4538]
* development -> rename to legacy-dev
* master -> rename to legacy-master ==> deploy to eventyay.com
* nextgen -> rename to development ==> deploy to staging.eventyay.com
* nextgen-backup -> rename to master ==> deploy to nextgen.eventyay.com
* delete staging branch

**Comment by 0x48piraj** [comment]
@mariobehling I can do it :smile: 
**Should I start ?**

**Comment by 0x48piraj** [comment]
> As @vaibhavsingh97 told me that this issue can be resolved by admin/maintainer only. I just wanted to know if I should move on to other issues? :blush:

**Comment by poush** [comment]
@0x48piraj the required changes has already been done.

**Comment by SaptakS** [comment]
Closing this issue since the repositories have been separated and the required branch naming done.
